from airflow import DAG
from datetime import datetime, timedelta
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator
from airflow.operators.email import EmailOperator


default_args = {
    'owner': 'hdu',
    'retries': 2,
    'retry_delay': timedelta(minutes=2)
}


def generate_report():
    print("=================================")
    print("       DAILY REPORT")
    print("=================================")

    sales = {
        "Monday": 1200,
        "Tuesday": 1800,
        "Wednesday": 1500,
        "Thursday": 2200,
        "Friday": 2500
    }

    total = sum(sales.values())
    average = total / len(sales)

    print("Sales:")
    
    for day, amount in sales.items():
        print(f"{day}: {amount}")

    print("")
    print(f"Total sales   : {total}")
    print(f"Average sales : {average}")
    print("Report generated successfully.")


with DAG(
    dag_id='dag_daily_report',
    default_args=default_args,
    start_date=datetime(2026, 9, 12),

    # 09:00 and 18:00 every day
    schedule='0 9,18 * * *',

    catchup=False
) as dag:

    start = EmptyOperator(
        task_id='start'
    )


    generate_report_task = PythonOperator(
        task_id='generate_report',
        python_callable=generate_report
    )


    send_email = EmailOperator(
        task_id='send_email',
        to='your_email@example.com',
        subject='Airflow Daily Report',
        html_content="""
        <h2>Airflow Daily Report</h2>

        <p>The daily report generation task has completed.</p>

        <p>
        This report was generated by an Airflow DAG
        using PythonOperator.
        </p>
        """
    )


    finish = EmptyOperator(
        task_id='finish'
    )


    #Until an Airflow email/SMTP connection configured
    #start >> generate_report_task >> send_email >> finish
    start >> generate_report_task >> finish
